### ISSUE TITLE
无法显示到微信验证的二维码

### ISSUE THREAD

**Issue by faifai8** [froger-me/wp-weixin#24] opened 2020-07-05 11:32 UTC
发现一个问题，电脑上面用Chrome、Firefox都无法显示到二维码，用Safari浏览器才可以。而在手机上，各个浏览器都可以显示到都没有问题。
![图片](https://user-images.githubusercontent.com/27717619/86531721-42ca2e00-bef6-11ea-98c6-cc5c9d5d8329.png)

**Comment by froger-me** [comment] 2020-07-29 12:56
Hi @hyuhui ; sorry for the late reply.\

Because of the lack of information (like: what is the URL of the broken image? What happens when visiting these URLs? What's the http response code when visiting the URL? Are permalinks properly generated? Does it happen after browser cache is cleared? etc, etc), I didn't spend more time pursuing. This issue can come from a variety of places. This issue does not happen on the several hundreds of sites using this plugin, and I do not know how to reproduce it.

I will close the issue now ; if you wish to pursue further, feel free to open a new one with more information to help troubleshooting.

**Closed as completed by froger-me** 2020-07-29 12:56 UTC
